baseURL = "/"
languageCode = "en-us"
title = "Schemes and Notions"
theme = "hugo-theme-m10c"

[params]
  avatar = "images/logo-Final.png"
  author = "Mike D"
  description  = "Ramblings and musings of a systems enginner and builder."
  menu_item_separator = " | "
 [[params.social]]
    icon = "user"
    name = "About Me"
    url = "https://www.zeroent.net"
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/mddeff"
 [[params.social]]
    icon = "brand-youtube"
    name = "Youtube"
    url = "https://www.youtube.com/channel/UCI_tKM35Gndgd18ifK7BghA"
 [[params.social]]
    icon = "brand-thingiverse"
    name = "Thingiverse"
    url = "https://www.thingiverse.com/mddeff/designs"

[params.style]
#  darkestColor = "#353b43"
#  darkColor = "#212121"
#  lightColor = "#f5e3e0"
#  lightestColor = "#eceff1"
  primaryColor = "#4f9edb"

[[menu.main]]
  identifier = "About"
  name       = "About Me"
  url        = "https://zeroent.net"
[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts"
[[menu.main]]
  identifier = "tags"
  name       = "Tags"
  url        = "/tags"
[[menu.main]]
  identifier = "rss"
  name       = "RSS Feed"
  url        = "/posts/index.xml"
